apiVersion: cli.tanzu.vmware.com/v1alpha1
kind: CLIPlugin
metadata:
  creationTimestamp: null
  name: apps
spec:
  artifacts:
    v0.5.1:
    - arch: amd64
      digest: ceb8b8e841ffcb2df7b8fb1b1e456332c2e6fffe60e86a9f4cb863d710708909
      os: linux
      type: local
      uri: linux/amd64/cli/apps/v0.5.1/tanzu-apps-linux_amd64
  description: Applications on Kubernetes
  optional: false
  recommendedVersion: v0.5.1
