apiVersion: cli.tanzu.vmware.com/v1alpha1
kind: CLIPlugin
metadata:
  creationTimestamp: null
  name: insight
spec:
  artifacts:
    v1.5.0:
    - arch: amd64
      digest: 31c38371aef95e4b9143f5e7c792eaf4a75e602daa0ee46f07c19223e46988d1
      os: linux
      type: local
      uri: linux/amd64/cli/insight/v1.5.0/tanzu-insight-linux_amd64
  description: post & query image, package, source, and vulnerability data
  optional: false
  recommendedVersion: v1.5.0
