apiVersion: cli.tanzu.vmware.com/v1alpha1
kind: CLIPlugin
metadata:
  creationTimestamp: null
  name: services
spec:
  artifacts:
    v0.6.0:
    - arch: amd64
      digest: 949128446f5d0b7096981c210ee4fd7eed35d01197124aef6b9729ef96eedc2a
      os: linux
      type: local
      uri: linux/amd64/cli/services/v0.6.0/tanzu-services-linux_amd64
  description: Commands for working with service instances, classes and claims
  optional: false
  recommendedVersion: v0.6.0
