images:
- name: springcloud/spring-cloud-dataflow-server # used for Kustomize matching
  newName: index.docker.io/oawofolu/spring-cloud-dataflow-server
  newTag: 1.4.5_scdf-k8s-1.4.3
  digest: sha256:46c3919d9355473e40578139ffc33b6cf4c8447c677fdb9e53f618664e1f8ca6
configMapGenerator:
- name: scdf-server
  files:
  - bootstrap.yaml
  - application.yaml
  - application-database.yaml
  - application-monitoring.yaml
bases:
- ../../base
patches:
- deployment-patch.yaml
- deployment-database-patch.yaml
- service-patch.yaml
