---
imagePullSecretName: tanzu-image-registry
operatorImage: registry.tanzu.vmware.com/tanzu-mysql-for-kubernetes/tanzu-mysql-operator:1.6.1
registry: "registry.tanzu.vmware.com/tanzu-mysql-for-kubernetes/"
resources: {}
#  limits:
#    cpu: 100m
#    memory: 128Mi
#  requests:
#    cpu: 100m
#    memory: 128Mi

certManagerClusterIssuerName: tanzu-sql-with-mysql-operator-ca-certificate-clusterissuer
