apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: rabbitcluster-uncompressed
spec:
  image: rabbitmq:3.9-management
  replicas: 3
  service:
    type: LoadBalancer
---
apiVersion: v1
kind: Secret
metadata:
  name: rabbitcluster-uncompressed-secret
type: Opaque
stringData:
  username: test-user
  password: test-password
---
apiVersion: rabbitmq.com/v1beta1
kind: User
metadata:
  name: rabbitmq-uncompressed
spec:
  rabbitmqClusterReference:
    name:  rabbitcluster-uncompressed
  importCredentialsSecret:
    name: rabbitcluster-uncompressed-secret
---
apiVersion: rabbitmq.com/v1beta1
kind: Permission
metadata:
  name: rabbitmq-uncompressed.all
spec:
  vhost: "/"
  userReference:
    name: rabbitmq-uncompressed
  permissions:
    write: ".*"
    configure: ".*"
    read: ".*"
  rabbitmqClusterReference:
    name: rabbitcluster-uncompressed
