apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: rabbitcluster1
spec:
  image: rabbitmq:3.10-management
  replicas: 3
  service:
    type: LoadBalancer
  rabbitmq:
    additionalPlugins:
      - rabbitmq_top
      - rabbitmq_shovel
      - rabbitmq_federation
      - rabbitmq_stream
      - rabbitmq_management
      - rabbitmq_prometheus
      - rabbitmq_peer_discovery_k8s