---
# credentials for the schema-replication user
apiVersion: v1
kind: Secret
metadata:
  name: rabbitcluster-upstream1-secret
type: Opaque
stringData:
  username: test-user
  password: test-password
---
# schema-replication user
apiVersion: rabbitmq.com/v1beta1
kind: User
metadata:
  name: rabbitmq-replicator
spec:
  rabbitmqClusterReference:
    name:  rabbitcluster-upstream1
  importCredentialsSecret:
    name: rabbitcluster-upstream1-secret
---
#permissions for the schema-replication user to access "test" vhost
apiVersion: rabbitmq.com/v1beta1
kind: Permission
metadata:
  name: rabbitmq-replicator.test.all
spec:
  vhost: "test"
  userReference:
    name: rabbitmq-replicator
  permissions:
    write: ".*"
    configure: ".*"
    read: ".*"
  rabbitmqClusterReference:
    name: rabbitcluster-upstream1
---
#permissions for the schema-replication user to access "rabbitmq_schema_definition_sync" vhost
apiVersion: rabbitmq.com/v1beta1
kind: Permission
metadata:
  name: rabbitmq-replicator.schema-definition-sync.all
spec:
  vhost: "rabbitmq_schema_definition_sync"
  userReference:
    name: rabbitmq-replicator
  permissions:
    write: ".*"
    configure: ".*"
    read: ".*"
  rabbitmqClusterReference:
    name: rabbitcluster-upstream1