---
apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: rabbitcluster2
spec:
  image: rabbitmq:3.10-management
  service:
    type: LoadBalancer
  rabbitmq:
    additionalPlugins:
      - rabbitmq_top
      - rabbitmq_shovel
      - rabbitmq_federation
      - rabbitmq_streams
---
apiVersion: rabbitmq.com/v1beta1
kind: Exchange
metadata:
  name: demo.topic.exchange
  namespace: rabbitmq-system
spec:
  name: demo.topic.exchange 
  type: topic 
  autoDelete: false
  durable: true
  rabbitmqClusterReference:
    name: rabbitcluster1
---
apiVersion: rabbitmq.com/v1beta1
kind: Binding
metadata:
  name: binding
  namespace: rabbitmq-system
spec:
  source: demo.topic.exchange
  destination: demo.quorum.green
  destinationType: queue
  rabbitmqClusterReference:
    name: rabbitcluster1
---
apiVersion: rabbitmq.com/v1beta1
kind: Binding
metadata:
  name: binding
  namespace: rabbitmq-system
spec:
  source: demo.topic.exchange
  destination: demo.classic.red
  destinationType: queue
  rabbitmqClusterReference:
    name: rabbitcluster1