apiVersion: secretgen.carvel.dev/v1alpha1
kind: SecretExport
metadata:
  name: image-pull-secret
  namespace: rabbitmq-system
spec:
  toNamespaces:
    - "*"
---
apiVersion: v1
kind: Secret
metadata:
  name: tanzu-rabbitmq-registry-creds
  namespace: YOUR_SESSION_NAMESPACE
  annotations:
    secretgen.carvel.dev/image-pull-secret: ""
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: e30K