apiVersion: rabbitmq.com/v1beta1
kind: SchemaReplication
metadata:
  name: rabbitcluster-downstream1
  namespace: YOUR_SESSION_NAMESPACE
spec:
  endpoints: "rabbitmq:5672"
  upstreamSecret:
    name: rabbitcluster-upstream1-secret
  rabbitmqClusterReference:
    name: rabbitcluster-downstream1