apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: rabbitcluster-compressed
spec:
  replicas: 3
  service:
    type: LoadBalancer
---
apiVersion: v1
kind: Secret
metadata:
  name: rabbitcluster-compressed-secret
type: Opaque
stringData:
  username: test-user
  password: test-password
---
apiVersion: rabbitmq.com/v1beta1
kind: User
metadata:
  name: rabbitmq-compressed
spec:
  rabbitmqClusterReference:
    name:  rabbitcluster-compressed
  importCredentialsSecret:
    name: rabbitcluster-compressed-secret
---
apiVersion: rabbitmq.com/v1beta1
kind: Permission
metadata:
  name: rabbitmq-compressed.all
spec:
  vhost: "/"
  userReference:
    name: rabbitmq-compressed
  permissions:
    write: ".*"
    configure: ".*"
    read: ".*"
  rabbitmqClusterReference:
    name: rabbitcluster-compressed
