---
apiVersion: rabbitmq.tanzu.vmware.com/v1beta1
kind: StandbyReplication
metadata:
  name: rabbitcluster-downstream1-configuration
spec:
  operatingMode: "downstream"
  downstreamModeConfiguration:
    endpoints: "rabbitcluster-upstream1:5552"
    upstreamSecret:
      name: rabbitcluster-downstream1-secret # an existing Kubernetes secret; required value
  rabbitmqClusterReference:
    name: rabbitcluster-downstream1