---
apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: image-processor
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: image-processor
spec:
  params:
    - name: clusterBuilder
      value: full
  env:
    - name: MLFLOW_TRACKING_URI
      value: http://mlflow-${SESSION_NAMESPACE}.${DATA_E2E_BASE_URL}
  source:
    git:
      url: https://github.com/${DATA_E2E_GIT_USER}/mlcode-runner.git
      ref:
        branch: main-${SESSION_NAMESPACE}