---
apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: image-processor
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: image-processor
  annotations:
    autoscaling.knative.dev/minScale: "1"
spec:
  params:
    - name: clusterBuilder
      value: full
    - name: api_descriptor
      value:
        type: openapi
        location:
          path: "/app/static/openapi.json"
          baseUrl: "http://image-processor-api..tanzumlai.com"
        system: image-processors
        owner: team-image-processors
        description: "A set of API endpoints for the ML Image Processing Demo App."
  env:
    - name: MLFLOW_TRACKING_URI
      value: http://mlflow-.tanzumlai.com
  source:
    git:
      url: https://github.com/tanzumlai/sample-ml-app.git
      ref:
        branch: main-
