apiVersion: apps/v1
kind: Deployment
metadata:
  name: skipper
  labels:
    app: skipper
spec:
  selector:
    matchLabels:
      app: skipper
  replicas: 1
  template:
    metadata:
      labels:
        app: skipper
    spec:
      containers:
      - name: skipper
        image: springcloud/spring-cloud-skipper-server
        imagePullPolicy: Always
        volumeMounts:
          - name: config
            mountPath: /workspace/runtime/config
            readOnly: true
        ports:
        - containerPort: 80
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 7577
          initialDelaySeconds: 90
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /actuator/info
            port: 7577
          initialDelaySeconds: 60
          periodSeconds: 15
        resources:
          limits:
            cpu: 1.0
            memory: 768Mi
          requests:
            cpu: 500m
            memory: 768Mi
        env:
        - name: SPRING_CONFIG_ADDITIONAL_LOCATION
          value: /workspace/runtime/config/
        - name: SPRING_CLOUD_KUBERNETES_CONFIG_ENABLE_API
          value: 'false'
        - name: SPRING_CLOUD_KUBERNETES_SECRETS_PATHS
          value: /workspace/runtime/secrets
      serviceAccountName: scdf-skipper
      volumes:
        - name: config
          configMap:
            name: skipper
