kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: skipper-rb
subjects:
- kind: ServiceAccount
  name: scdf-skipper
roleRef:
  kind: Role
  name: skipper-role
  apiGroup: rbac.authorization.k8s.io
