apiVersion: v1
kind: Secret
metadata:
  name: registry-credentials
  annotations:
    secretgen.carvel.dev/image-pull-secret: ""
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: e30K
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: tap-default
rules:
  - apiGroups: [source.toolkit.fluxcd.io]
    resources: [gitrepositories]
    verbs: ['*']
  - apiGroups: [source.apps.tanzu.vmware.com]
    resources: [imagerepositories]
    verbs: ['*']
  - apiGroups: [carto.run]
    resources: [deliverables, runnables]
    verbs: ['*']
  - apiGroups: [kpack.io]
    resources: [images]
    verbs: ['*']
  - apiGroups: [conventions.apps.tanzu.vmware.com]
    resources: [podintents]
    verbs: ['*']
  - apiGroups: [""]
    resources: ['configmaps']
    verbs: ['*']
  - apiGroups: [""]
    resources: ['pods']
    verbs: ['list']
  - apiGroups: [tekton.dev]
    resources: [taskruns, pipelineruns]
    verbs: ['*']
  - apiGroups: [tekton.dev]
    resources: [pipelines]
    verbs: ['list']
  - apiGroups: [kappctrl.k14s.io]
    resources: [apps]
    verbs: ['*']
  - apiGroups: [serving.knative.dev]
    resources: ['services']
    verbs: ['*']
  - apiGroups: [servicebinding.io]
    resources: ['servicebindings']
    verbs: ['*']
  - apiGroups: [services.apps.tanzu.vmware.com]
    resources: ['resourceclaims']
    verbs: ['*']
  - apiGroups: [scanning.apps.tanzu.vmware.com]
    resources: ['imagescans', 'sourcescans']
    verbs: ['*']
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: tap-default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: tap-default
subjects:
  - kind: ServiceAccount
    name: default