# permissions for end users to edit postgresbackupschedules.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: postgresbackupschedule-editor-role
rules:
- apiGroups:
  - sql.tanzu.vmware.com
  resources:
  - postgresbackupschedules
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - sql.tanzu.vmware.com
  resources:
  - postgresbackupschedules/status
  verbs:
  - get
