apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    rbac.authorization.k8s.io/aggregate-to-view: "true"
    rbac.authorization.k8s.io/aggregate-to-edit: "true"
    app: postgres-operator
  name: postgres-viewer
rules:
  - apiGroups:
      - sql.tanzu.vmware.com
    resources:
      - postgres
    verbs:
      - get
      - list
      - watch
