spring:
  cloud:
    skipper:
      server:
        platform:
          kubernetes:
            accounts:
              default:
                limits:
                  memory: 1024Mi
                  cpu: 400m
                requests:
                  memory: 1024Mi
                  cpu: 200m
                readinessProbeDelay: 90
                livenessProbeDelay: 120
      security:
        authorization:
          permit-all-paths: "/actuator/health,/actuator/info,/authenticate,/security/info,/features,/assets/**,/dashboard/logout-success-oauth.html"
