apiVersion: apps/v1
kind: Deployment
metadata:
  name: skipper
spec:
  template:
    spec:
      containers:
      - name: skipper
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: database,broker
        resources:
          limits:
            cpu: 1.0
            memory: 1024Mi
          requests:
            cpu: 500m
            memory: 1024Mi
      imagePullSecrets:
      - name: scdf-image-regcred
