---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kube-dns
  namespace: kube-system
data:
  stubDomains: |
    {
      "YOUR_SESSION_NAMESPACE.svc.cluster.local": ["PRIMARY_ISTIO_INGRESS_HOSTNAME"]
    }