---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kube-dns
  namespace: kube-system
data:
  stubDomains: |
    {
      "YOUR_SESSION_NAMESPACE-remote.svc.cluster.local": ["SECONDARY_ISTIO_INGRESS_HOSTNAME"]
    }