apiVersion: gemfire.tanzu.vmware.com/v1
kind: GemFireCluster
metadata:
  name: gemfire1
spec:
  image: registry.pivotal.io/tanzu-gemfire-for-kubernetes/gemfire-k8s:1.0.1
  #! servers:
  #!  overrides:
  #!    gemfireProperties:
  #!      start-dev-rest-api: "true"