apiVersion: gemfire.tanzu.vmware.com/v1
kind: GemFireCluster
metadata:
  name: gemfire1
spec:
  image: registry.pivotal.io/tanzu-gemfire-for-kubernetes/gemfire-k8s:1.0.3
  serialization:
    pdx:
      readSerialized: true
  servers:
    overrides:
      gemfireProperties:
        start-dev-rest-api: "true"
        mcast-port: "0"
        distributed-system-id: "1"
        remote-locators: "gemfire2-locator-0.gemfire2-locator.YOUR_SESSION_NAMESPACE.svc.cluster.local[10334]"
---
apiVersion: v1
kind: Service
metadata:
  name: gemfire1-dev-api
spec:
  selector:
    app: gemfire1-server
  ports:
    - name: rest-api
      port: 7070
      targetPort: 7070
  type: LoadBalancer