apiVersion: gemfire.vmware.com/v1
kind: GemFireCluster
metadata:
  name: gemfire-cluster
spec:
  image: registry.tanzu.vmware.com/pivotal-gemfire/vmware-gemfire:10.0.0
  security:
    tls: { }
  serialization:
    pdx:
      readSerialized: true
  locators:
    overrides:
      jvmOptions:
        - "-Djava.net.preferIPv4Stack=true"
  servers:
    overrides:
      jvmOptions:
        - "-Djava.net.preferIPv4Stack=true"
      gemFireProperties:
        - name: "start-dev-rest-api"
          value: "true"


