---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: greenplum-training-external-secret
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: greenplum-training-secret
  data:
    - secretKey: greenplum_pem_file
      remoteRef:
        key: secret/greenplum/default/training
        property: pem
    - secretKey: greenplum_master_password
      remoteRef:
        key: secret/greenplum/default/training
        property: password
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: postgres-inference-external-secret
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: postgres-inference-secret
  data:
    - secretKey: postgres_password
      remoteRef:
        key: secret/postgres/default/inference
        property: password

