#@ load("@ytt:data", "data")
#@ load("@ytt:yaml", "yaml")
---
apiVersion: batch/v1
kind: Job
metadata:
  name: #@ "resubmit-workflow-" + data.read(data.values.environment_name).strip()
  annotations:
    kapp.k14s.io/change-group: "apps.big.co/llm-argo-pipeline-job"
    kapp.k14s.io/change-rule: "upsert before upserting apps.big.co/llm-argo-pipelines"
spec:
  template:
    spec:
      containers:
        - name: resubmit-workflow
          image: oawofolu/argocli:latest
          command: [/bin/sh]
          args: ["-c", "argo resubmit --log llm-image-processing-workflow-${SESSION_NAMESPACE} || true"]
      restartPolicy: Never
  backoffLimit: 0
  podFailurePolicy:
    rules:
      - action: Ignore
        onExitCodes:
          operator: NotIn
          values: [ 4200000 ]
---
apiVersion: kapp.k14s.io/v1alpha1
kind: Config
rebaseRules:
  - paths:
      - [spec]
      - [metadata, annotations]
      - [metadata, labels]
    type: copy
    sources: [existing]
    resourceMatchers:
      - apiVersionKindMatcher: {apiVersion: argoproj.io/v1alpha1, kind: Workflow}