apiVersion: kappctrl.k14s.io/v1alpha1
kind: App
metadata:
  name: mlapp-kfp-${SESSION_NAMESPACE}
spec:
  serviceAccountName: default
  fetch:
    - git:
        url: https://github.com/${DATA_E2E_GIT_USER}/sample-ml-app
        ref: origin/kfp-main-${SESSION_NAMESPACE}
    - http:
        url: https://api.github.com/repos/${DATA_E2E_GIT_USER}/sample-ml-app/commits/kfp-main-${SESSION_NAMESPACE}

  template:
    - ytt:
        paths:
          - 0/pipeline.yaml
          - 0/values.yaml
          - 1/kfp-main-${SESSION_NAMESPACE}

  deploy:
    - kapp: {}