#@data/values
---
model_stage: Staging
git_repo: https://github.com/${DATA_E2E_GIT_USER}/sample-ml-app.git
experiment_name: convolutional_neural_network_team_${SESSION_NAMESPACE}
environment_name: main-${SESSION_NAMESPACE}
mlflow_tracking_uri: http://mlflow-${SESSION_NAMESPACE}.${DATA_E2E_BASE_URL}
mlflow_s3_uri: http://minio-${SESSION_NAMESPACE}.${DATA_E2E_BASE_URL}