apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: minio-bitnami-console-httpproxy
  namespace: minio
spec:
  virtualhost:
    fqdn: minio-console.${DATA_E2E_BASE_URL}
    tls:
      passthrough: true
  tcpproxy:
    services:
      - name: minio
        port: 9001
---
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: minio-bitnami-httpproxy
  namespace: minio
spec:
  virtualhost:
    fqdn: minio.${DATA_E2E_BASE_URL}
    tls:
      passthrough: true
  tcpproxy:
    services:
      - name: minio
        port: 9000


