apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: minio-plain-httpproxy
  namespace: minio-plain
spec:
  routes:
    - conditions:
        - prefix: /
      services:
        - name: minio
          port: 9000
  virtualhost:
    fqdn: minio-plain.${DATA_E2E_BASE_URL}
    
