---
apiVersion: v1
kind: Service
metadata:
  name: minio-tls-service
  namespace: minio-tls
spec:
  selector:
    name: minio
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9000
  type: LoadBalancer
