apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: generic
  annotations:
    kapp.k14s.io/update-strategy: always-replace
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: kubernetes.io/gce-pd
reclaimPolicy: Delete
allowVolumeExpansion: true
volumeBindingMode: WaitForFirstConsumer
parameters:
  type: pd-standard
  fstype: ext4
  replication-type: none