apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: tap-gui-httpproxy
  namespace: tap-gui
spec:
  routes:
  - conditions:
    - prefix: /
    services:
    - name: server
      port: 7000
  virtualhost:
    fqdn: tap-gui.${DATA_E2E_BASE_URL}