images:
- name: springcloud/spring-cloud-skipper-server # used for Kustomize matching
  newName: registry.pivotal.io/p-scdf-for-kubernetes/spring-cloud-skipper-server
  newTag: 2.7.0_scdf-k8s-1.3.0
  digest: sha256:4d4fd0ba0bcfd866ae48275121a77674358f724d61286a9c84f33b7afdba709d
configMapGenerator:
- name: skipper
  files:
  - bootstrap.yaml
  - application.yaml
  - application-database.yaml
  - application-broker.yaml
bases:
- ../../base
patches:
- deployment-patch.yaml
- deployment-database-patch.yaml
- deployment-broker-patch.yaml
- service-patch.yaml
