images:
- name: springcloud/spring-cloud-dataflow-server # used for Kustomize matching
  newName: registry.pivotal.io/p-scdf-for-kubernetes/spring-cloud-dataflow-pro-server
  newTag: 1.3.0_scdf-k8s-1.3.0
  digest: sha256:623464297957667f2ac93e8709d4241da02ec1a2b05d2f02571631e0c1a458f7
configMapGenerator:
- name: scdf-server
  files:
  - bootstrap.yaml
  - application.yaml
  - application-database.yaml
bases:
- ../../base
patches:
- deployment-patch.yaml
- deployment-database-patch.yaml
- service-patch.yaml
#!generatorOptions:
#!  disableNameSuffixHash: true
