apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    rbac.authorization.k8s.io/aggregate-to-edit: "true"
    app: postgres-operator
  name: postgres-editor
rules:
  - apiGroups:
      - sql.tanzu.vmware.com
    resources:
      - postgres
    verbs:
      - create
      - delete
      - deletecollection
      - patch
      - update
