---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: postgres-operator-cluster-role
  labels:
    app: postgres-operator
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - create
      - delete
      - get
      - list
      - update
      - watch
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - create
      - patch
  - apiGroups:
      - ""
    resources:
      - persistentvolumeclaims
    verbs:
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - ""
    resources:
      - pods/exec
    verbs:
      - create
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - ""
    resources:
      - secrets/finalizers
      - services/finalizers
    verbs:
      - update
  - apiGroups:
      - ""
    resources:
      - serviceaccounts
    verbs:
      - create
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - ""
    resources:
      - services
    verbs:
      - create
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - apps
    resources:
      - statefulsets
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - apps
    resources:
      - statefulsets/finalizers
    verbs:
      - update
  - apiGroups:
      - apps
    resources:
      - statefulsets/status
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - batch
    resources:
      - cronjobs
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - batch
    resources:
      - jobs
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - cert-manager.io
    resources:
      - certificates
    verbs:
      - create
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - cert-manager.io
    resources:
      - certificates/finalizers
    verbs:
      - update
  - apiGroups:
      - rbac.authorization.k8s.io
    resources:
      - rolebindings
      - roles
    verbs:
      - create
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - rbac.authorization.k8s.io
    resources:
      - roles/finalizers
    verbs:
      - update
  - apiGroups:
      - sql.tanzu.vmware.com
    resources:
      - postgres
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - sql.tanzu.vmware.com
    resources:
      - postgres/finalizers
    verbs:
      - update
  - apiGroups:
      - sql.tanzu.vmware.com
    resources:
      - postgres/status
    verbs:
      - create
      - get
      - patch
      - update
  - apiGroups:
      - sql.tanzu.vmware.com
    resources:
      - postgresbackuplocations
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - sql.tanzu.vmware.com
    resources:
      - postgresbackuplocations/status
    verbs:
      - get
      - patch
      - update
  - apiGroups:
      - sql.tanzu.vmware.com
    resources:
      - postgresbackups
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - sql.tanzu.vmware.com
    resources:
      - postgresbackups/status
    verbs:
      - get
      - update
  - apiGroups:
      - sql.tanzu.vmware.com
    resources:
      - postgresbackupschedules
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - sql.tanzu.vmware.com
    resources:
      - postgresbackupschedules/status
    verbs:
      - get
      - patch
      - update
  - apiGroups:
      - sql.tanzu.vmware.com
    resources:
      - postgresrestores
    verbs:
      - get
      - list
      - update
      - watch
  - apiGroups:
      - sql.tanzu.vmware.com
    resources:
      - postgresrestores/status
    verbs:
      - get
      - list
      - update
      - watch
  - apiGroups:
      - sql.tanzu.vmware.com
    resources:
      - postgresversions
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - sql.tanzu.vmware.com
    resources:
      - postgresversions/finalizers
    verbs:
      - update
  - apiGroups:
      - sql.tanzu.vmware.com
    resources:
      - postgresversions/status
    verbs:
      - get
      - patch
      - update
