apiVersion: secretgen.carvel.dev/v1alpha1
kind: SecretExport
metadata:
  name: pginstance-1-app-user-db-secret
  namespace: YOUR_SESSION_NAMESPACE
spec:
  toNamespaces:
    - "*"
---
apiVersion: secretgen.carvel.dev/v1alpha1
kind: SecretImport
metadata:
  name: pginstance-1-app-user-db-secret
  namespace: pgadmin-YOUR_SESSION_NAMESPACE
spec:
  fromNamespace: YOUR_SESSION_NAMESPACE