---
apiVersion: bindings.labs.vmware.com/v1alpha1
kind: ProvisionedService
metadata:
  name: pginstance-1
spec:
  binding:
    name: pginstance-1-app-user-db-secret
---
apiVersion: servicebinding.io/v1beta1
kind: ServiceBinding
metadata:
  name: pginstance-1
spec:
  service:
    apiVersion: bindings.labs.vmware.com/v1alpha1
    kind: ProvisionedService
    name: pginstance-1
  workload:
    apiVersion: apps/v1
    kind: Deployment
    name: pgadmin-pgadmin4