apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: tanzu-postgres-instances
  namespace: monitoring-tools
  labels:
    release: prometheus
spec:
  namespaceSelector:
    any: true
  selector:
    matchLabels:
      type: data
      app: postgres
  podTargetLabels:
    - postgres-instance
  podMetricsEndpoints:
    - port: "metrics"
      interval: "10s"
      scheme: https
      tlsConfig:
        insecureSkipVerify: true