# permissions for end users to view postgresbackupschedules.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: postgresbackupschedule-viewer-role
rules:
- apiGroups:
  - sql.tanzu.vmware.com
  resources:
  - postgresbackupschedules
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - sql.tanzu.vmware.com
  resources:
  - postgresbackupschedules/status
  verbs:
  - get
