---
apiVersion: v1
kind: Service
metadata:
  name: postgres-operator-webhook-service
  labels:
    app: postgres-operator
spec:
  ports:
    - port: 443
      targetPort: 9443
  selector:
    app: postgres-operator
