---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: postgres-operator-cluster-role
  labels:
    app: postgres-operator
rules:
- apiGroups: [apiextensions.k8s.io]
  resources: [customresourcedefinitions]
  verbs: ['*']
- apiGroups: [certificates.k8s.io]
  resources: [certificatesigningrequests]
  verbs: ['*']
- apiGroups: [certificates.k8s.io]
  resources: [certificatesigningrequests/approval]
  verbs: ['*']
- apiGroups: [ cert-manager.io ]
  resources: [ certificates ]
  verbs: [ '*' ]
- apiGroups: [admissionregistration.k8s.io]
  resources: [validatingwebhookconfigurations]
  verbs: ['*']
- apiGroups: [ rbac.authorization.k8s.io ]
  resources:
    - roles
    - rolebindings
  verbs: [ '*' ]
- apiGroups: [sql.tanzu.vmware.com]
  resources: [postgres]
  verbs: ['*']
- apiGroups: [sql.tanzu.vmware.com]
  resources: [postgresbackuplocations]
  verbs: ['*']
- apiGroups: [sql.tanzu.vmware.com]
  resources: [postgresbackuplocations/status]
  verbs: ['*']
- apiGroups: [sql.tanzu.vmware.com]
  resources: [postgresbackups]
  verbs: ['*']
- apiGroups: [sql.tanzu.vmware.com]
  resources: [postgresbackupschedules]
  verbs: ['*']
- apiGroups: [sql.tanzu.vmware.com]
  resources: [postgresbackupschedules/status]
  verbs: ['*']
- apiGroups: [sql.tanzu.vmware.com]
  resources: [postgresversions]
  verbs: ['*']
- apiGroups: [sql.tanzu.vmware.com]
  resources: [postgresversions/status]
  verbs:
    - get
- apiGroups: [apps]
  resources: [deployments]
  verbs: ['*']
- apiGroups: [apps]
  resources: [statefulsets]
  verbs: ['*']
- apiGroups: [""]
  resources:
  - configmaps
  - secrets
  verbs: ['*']
- apiGroups: [""]
  resources:
  - statefulsets
  - pods
  - nodes
  - services
  - endpoints
  - persistentvolumeclaims
  - events
  - serviceaccounts
  verbs: ['*']
- apiGroups: [""]
  resources:
  - services
  - endpoints
  verbs:
  - get
  - create
  - update
- apiGroups: [""]
  resources: [nodes]
  verbs:
  - list
  - watch
- apiGroups: [""]
  resources: [namespaces]
  verbs:
  - list
  - watch
- apiGroups: [""]
  resources: ["pods/exec"]
  verbs: ["create"]
- apiGroups: [batch]
  resources:
  - cronjobs
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
