# permissions for end users to view postgresversions.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: postgresversion-viewer-role
rules:
- apiGroups:
  - sql.tanzu.vmware.com
  resources:
  - postgresversions
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - sql.tanzu.vmware.com
  resources:
  - postgresversions/status
  verbs:
  - get
