#@ load("@ytt:data", "data")
#@ load("@ytt:json", "json")
---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name:  #@ "ml-image-processing-pipeline-kfpmain-{}".format(json.decode(data.read(kfp-main-${SESSION_NAMESPACE}))["sha"])
spec:
  template:
    spec:
      containers:
        - image: ${DATA_E2E_REGISTRY_USERNAME}/ml-image-processor-kfp
          ports:
            - containerPort: 8080
          env:
            - name: MLFLOW_STAGE
              value: #@ data.values.model_stage
            - name: GIT_REPO
              value: https://github.com/${DATA_E2E_GIT_USER}/sample-ml-app
            - name: EXPERIMENT_NAME
              value: #@ data.values.experiment_name
            - name: ENVIRONMENT_NAME
              value: #@ data.values.environment_name
            - name: KUBEFLOW_PIPELINES_HOST
              value: #@ data.values.kfp_host
            - name: USE_CACHE
              value: #@ data.values.use_cache