#@ load("@ytt:data", "data")
---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: ml-image-processing-pipeline-kfpmain
spec:
  template:
    spec:
      containers:
        - image: oawofolu/ml-image-processor-kfp
          ports:
            - containerPort: 8080
          env:
            - name: MLFLOW_STAGE
              value: #@ data.values.model_stage
            - name: GIT_REPO
              value: #@ data.values.git_repo
            - name: EXPERIMENT_NAME
              value: #@ data.values.experiment_name
            - name: ENVIRONMENT_NAME
              value: #@ data.values.environment_name
            - name: KUBEFLOW_PIPELINES_HOST
              value: #@ data.values.kfp_host
            - name: USE_CACHE
              value: #@ data.values.use_cache