---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-operator
  namespace: default
  labels:
    app: postgres-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-operator
  template:
    metadata:
      labels:
        app: postgres-operator
    spec:
      serviceAccountName: postgres-operator-service-account
      containers:
        - name: postgres-operator
          image: {{ .Values.operatorImageRepository }}:{{ .Values.operatorImageTag }}
          command: ["./manager", "--webhook-cert-directory", "/tmp/postgres-operator-webhook-server-cert-secret"]
          imagePullPolicy: IfNotPresent
          env:
          - name: POSTGRES_IMAGE_REPO
            value: {{ .Values.postgresImageRepository }}
          - name: POSTGRES_IMAGE_TAG
            value: {{ .Values.postgresImageTag }}
          - name: OPERATOR_IMAGE_REPO
            value: {{ .Values.operatorImageRepository }}
          - name: OPERATOR_IMAGE_TAG
            value: {{ .Values.operatorImageTag }}
          - name: DOCKER_REGISTRY_SECRET_NAME
            value: {{ .Values.dockerRegistrySecretName }}
          readinessProbe:
            exec:
              command:
                - cat
                - /tmp/operatorReady
            initialDelaySeconds: 3
            periodSeconds: 2
          ports:
            - containerPort: 9443
              name: webhook-server
              protocol: TCP
          volumeMounts:
            - mountPath: /tmp/postgres-operator-webhook-server-cert-secret
              name: postgres-operator-webhook-server-cert-secret
              readOnly: true
      imagePullSecrets:
        - name: {{ .Values.dockerRegistrySecretName }}
      volumes:
        - name: postgres-operator-webhook-server-cert-secret
          secret:
            defaultMode: 420
            secretName: postgres-operator-webhook-server-cert
