# Queue Binding
---
apiVersion: rabbitmq.com/v1beta1
kind: Binding
metadata:
  name: rabbitanalytics4-binding
spec:
  source: rabbitanalytics4-stream-exchange
  destination: rabbitanalytics4-stream
  destinationType: queue
  routingKey: "anomaly.#"
  rabbitmqClusterReference:
    name: rabbitanalytics4

---
# For PROD
apiVersion: rabbitmq.com/v1beta1
kind: Binding
metadata:
  name: rabbitanalytics4-stats-binding
spec:
  source: rabbitanalytics4-exchange
  destination: rabbitanalytics4-stats
  destinationType: queue
  routingKey: "anomaly.stats"
  rabbitmqClusterReference:
    name: rabbitanalytics4

---
# For ARIMA
apiVersion: rabbitmq.com/v1beta1
kind: Binding
metadata:
  name: rabbitanalytics4-stats-binding-arima
spec:
  source: rabbitanalytics4-exchange
  destination: rabbitanalytics4-stats-arima
  destinationType: queue
  routingKey: "anomaly.stats"
  rabbitmqClusterReference:
    name: rabbitanalytics4

---
# For RNN
apiVersion: rabbitmq.com/v1beta1
kind: Binding
metadata:
  name: rabbitanalytics4-stats-binding-rnn
spec:
  source: rabbitanalytics4-exchange
  destination: rabbitanalytics4-stats-rnn
  destinationType: queue
  routingKey: "anomaly.stats"
  rabbitmqClusterReference:
    name: rabbitanalytics4

---
# For PROD
apiVersion: rabbitmq.com/v1beta1
kind: Binding
metadata:
  name: rabbitanalytics4-dashboard-binding
spec:
  source: rabbitanalytics4-exchange
  destination: rabbitanalytics4-dashboard
  destinationType: queue
  routingKey: "anomaly.datapublished"
  rabbitmqClusterReference:
    name: rabbitanalytics4

---
# For ARIMA
apiVersion: rabbitmq.com/v1beta1
kind: Binding
metadata:
  name: rabbitanalytics4-dashboard-binding-arima
spec:
  source: rabbitanalytics4-exchange
  destination: rabbitanalytics4-dashboard-arima
  destinationType: queue
  routingKey: "anomaly.datapublished"
  rabbitmqClusterReference:
    name: rabbitanalytics4

---
# For RNN
apiVersion: rabbitmq.com/v1beta1
kind: Binding
metadata:
  name: rabbitanalytics4-dashboard-binding-rnn
spec:
  source: rabbitanalytics4-exchange
  destination: rabbitanalytics4-dashboard-rnn
  destinationType: queue
  routingKey: "anomaly.datapublished"
  rabbitmqClusterReference:
    name: rabbitanalytics4

---
# For PROD
apiVersion: rabbitmq.com/v1beta1
kind: Binding
metadata:
  name: rabbitanalytics4-inference-binding
spec:
  source: rabbitanalytics4-exchange
  destination: rabbitanalytics4-inference
  destinationType: queue
  routingKey: "anomaly.datapublished"
  rabbitmqClusterReference:
    name: rabbitanalytics4

---
# For ARIMA
apiVersion: rabbitmq.com/v1beta1
kind: Binding
metadata:
  name: rabbitanalytics4-inference-binding-arima
spec:
  source: rabbitanalytics4-exchange
  destination: rabbitanalytics4-inference-arima
  destinationType: queue
  routingKey: "anomaly.datapublished"
  rabbitmqClusterReference:
    name: rabbitanalytics4

---
# For RNN
apiVersion: rabbitmq.com/v1beta1
kind: Binding
metadata:
  name: rabbitanalytics4-inference-binding-rnn
spec:
  source: rabbitanalytics4-exchange
  destination: rabbitanalytics4-inference-rnn
  destinationType: queue
  routingKey: "anomaly.datapublished"
  rabbitmqClusterReference:
    name: rabbitanalytics4
