---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: tanzu-mysql-instances
  namespace: prometheus
spec:
  namespaceSelector:
    any: true
  selector:
    matchLabels:
    app.kubernetes.io/component: database
    app.kubernetes.io/name: mysql
  podTargetLabels:
    - app.kubernetes.io/instance
  podMetricsEndpoints:
    - port: "mysql-metrics"
      interval: "10s"
      scheme: https
      tlsConfig:
        insecureSkipVerify: true