apiVersion: kpack.io/v1alpha2
kind: Image
metadata:
  name: imgprocessor-kfp
spec:
  tag: oawofolu/ml-image-processor-kfp
  builder:
    kind: ClusterBuilder
    name: full
  source:
    git:
      url: https://github.com/agapebondservant/ml-image-processing-app-kfpipeline-driver.git
      revision: main
  cache:
    volume:
      size: 8G