apiVersion: kpack.io/v1alpha2
kind: Image
metadata:
  name: imgprocessor
spec:
  tag: oawofolu/ml-image-processor-
  builder:
    kind: ClusterBuilder
    name: full
  source:
    git:
      url: https://github.com/tanzumlai/sample-ml-app.git
      revision: main-
  cache:
    volume:
      size: 8G
  build:
    env:
      - name: "MLFLOW_TRACKING_URI"
        value: http://mlflow-.tanzumlai.com
      - name: "MLFLOW_S3_ENDPOINT_URL"
        value: http://minio-.tanzumlai.com