apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: operator-httpproxy
spec:
  routes:
  - conditions:
    - prefix: /
    services:
    - name: tanzu-operator-ui-svc
      port: 8080
  virtualhost:
    fqdn: operator-ui.tanzuwandemo.ml
