apiVersion: v1
kind: Pod
metadata:
  name: tanzu-operator-ui-app
  labels:
    app: tanzu-operator-ui
spec:
  containers:
  - name: ui
    image: ubuntu:latest
    command: ['sh', '-c', '/ui/tanzusql-ui-linux -kubeconfig=/kconfig/.config -open-browser=false -address=0.0.0.0:8080']
    ports:
      - containerPort: 8080
    volumeMounts:
      - mountPath: /ui
        name: ui-volume
      - mountPath: /kconfig
        name: config-volume
  volumes:
    - name: ui-volume
      emptyDir: { }
    - name: config-volume
      configMap:
        name: kconfig
  initContainers:
  - name: init-myservice
    image: alpine/git
    imagePullPolicy: Always
    volumeMounts:
      - mountPath: /ui
        name: ui-volume
    args:
      - clone
      - '--single-branch'
      - '--'
      - 'https://github.com/agapebondservant/tanzu-operator-ui.git'
      - '/ui'
