spring:
  datasource:
    url: jdbc:mysql://mysql:3306/dataflow
    username: mysqluser
    password: ${database-password}
    driverClassName: org.mariadb.jdbc.Driver
    testOnBorrow: true
    validationQuery: "SELECT 1"
