images:
- name: springcloud/spring-cloud-skipper-server # used for Kustomize matching
  newName: index.docker.io/oawofolu/spring-cloud-skipper-server
  newTag: 2.8.4_scdf-k8s-1.4.3
  digest: sha256:b2c8989c19662cfcf3a912910533a4755d8060a1ec51f8575dd0bdff62189fe0
configMapGenerator:
- name: skipper
  files:
  - bootstrap.yaml
  - application.yaml
  - application-database.yaml
  - application-broker.yaml
bases:
- ../../base
patches:
- deployment-patch.yaml
- deployment-database-patch.yaml
- deployment-broker-patch.yaml
- service-patch.yaml
