# permissions for end users to edit postgresversions.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: postgresversion-editor-role
rules:
- apiGroups:
  - sql.tanzu.vmware.com
  resources:
  - postgresversions
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - sql.tanzu.vmware.com
  resources:
  - postgresversions/status
  verbs:
  - get
