kind: Service
apiVersion: v1
metadata:
  name: scdf-server
  labels:
    app: scdf-server
    spring-deployment-id: scdf
spec:
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: scdf-server
